### ISSUE TITLE
Problem inserting using PostPointAsync

### ISSUE THREAD

**Issue by jppf** [AdysTech/InfluxDB.Client.Net#92]
Hi, first of all a big thanks for your project here and all your effort in keeping improving it!

I had Task.Run( async () => { var x = await influx.PostPointAsync(dbName, point) }); and this wasn't placing all the data in influxdb.
In other try i created a list = List<task> and used var t = Task.Run("the same as above");
So i could do Task.WaitAll(list.ToArray()); And i got in other problems and had a lot of exceptions throwing with Task - one or more errors occured. 

So after all that, i decided to go back my earliest version, and just do Task.Run( async () => {} var x = await influx.PostPointAsync(dbName, point)).GetAwaiter().GetResult(); forcing insertion one at a time and all data at least was getting inserted, not taking advantage of the async but having data integrity.
And now a new problem has appeared.

This is the stacktrace of the error.
3/18/2020 5:24:49 PM - Timer T1 - measurement='00103' tag='CAMPOSTR06_T' value='474055656' dropped=1
   at AdysTech.InfluxDB.Client.Net.InfluxDBClient.<PostPointAsync>d__25.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at malcom.Manager.<>c__DisplayClass8_1.<<Ora_Select_and_Insert_Inf>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at malcom.Manager.Ora_Select_and_Insert_Inf(Indicator i, Int32 hour)
3/19/2020 5:23:03 AM - Timer T1 - measurement='00103' tag='CAMPOSTR06_T' value='E0004PT1602000000000000ZB20000000481237' dropped=1
   at AdysTech.InfluxDB.Client.Net.InfluxDBClient.<PostPointAsync>d__25.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at malcom.Manager.<>c__DisplayClass8_1.<<Ora_Select_and_Insert_Inf>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at malcom.Manager.Ora_Select_and_Insert_Inf(Indicator i, Int32 hour)
3/19/2020 1:22:42 PM - Timer T1 - measurement='00103' tag='CAMPOSTR06_T' value='E0004PT1602000000000000ZB20000000483467' dropped=1
   at AdysTech.InfluxDB.Client.Net.InfluxDBClient.<PostPointAsync>d__25.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at malcom.Manager.<>c__DisplayClass8_1.<<Ora_Select_and_Insert_Inf>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at malcom.Manager.Ora_Select_and_Insert_Inf(Indicator i, Int32 hour).

i cant understand what to do. this is my code. on getting the influx point

Thanks :)

![image](https://user-images.githubusercontent.com/24211737/77169072-ce878e00-6ab0-11ea-9d76-b8e3b7133fb6.png)

**Comment by jppf** [comment]
![image](https://user-images.githubusercontent.com/24211737/77169740-e90e3700-6ab1-11ea-9212-da38e403d2af.png)
this is my code on inserting

**Comment by mvadu** [comment]
Your error does not indicate any errors with the library. Its mostly due to your data. Can you put a break point on your line just before `var x = await PostPointAsync` and get me output of  `ConvertToInfluxLineProtocol` from your `getInfluxDataPoint`?

**Comment by jppf** [comment]
Yes, you are right! It was a problem with the data.
Thanks! Keep up the good work :)
