### ISSUE TITLE
ARM64 compatibility

### ISSUE THREAD

**Issue by DanielPeinhopf** [AdysTech/InfluxDB.Client.Net#95]
Is this library compatible to ARM64?
I'am trying to insert a point on an Armbian system running on a Nano Pi Neo Core 2 but i'am getting the following error message:

> System.IO.Compression.ZLibException: The underlying compression routine could not be loaded correctly.
 ---> System.DllNotFoundException: Unable to load shared library 'System.IO.Compression.Native' or one of its dependencies. In order to help diagnose loading problems, consider setting the LD_DEBUG environment variable: libSystem.IO.Compression.Native: cannot open shared object file: No such file or directory
   at Interop.zlib.DeflateInit2_(ZStream& stream, CompressionLevel level, CompressionMethod method, Int32 windowBits, Int32 memLevel, CompressionStrategy strategy)
   at System.IO.Compression.ZLibNative.ZLibStreamHandle.DeflateInit2_(CompressionLevel level, Int32 windowBits, Int32 memLevel, CompressionStrategy strategy)
   at System.IO.Compression.Deflater.DeflateInit(CompressionLevel compressionLevel, Int32 windowBits, Int32 memLevel, CompressionStrategy strategy)
   --- End of inner exception stack trace ---
   at System.IO.Compression.Deflater.DeflateInit(CompressionLevel compressionLevel, Int32 windowBits, Int32 memLevel, CompressionStrategy strategy)
   at System.IO.Compression.Deflater..ctor(CompressionLevel compressionLevel, Int32 windowBits)
   at System.IO.Compression.DeflateStream.InitializeDeflater(Stream stream, Boolean leaveOpen, Int32 windowBits, CompressionLevel compressionLevel)
   at System.IO.Compression.DeflateStream..ctor(Stream stream, CompressionMode mode, Boolean leaveOpen, Int32 windowBits, Int64 uncompressedSize)
   at System.IO.Compression.GZipStream..ctor(Stream stream, CompressionMode mode, Boolean leaveOpen)
   at AdysTech.InfluxDB.Client.Net.InfluxDBClient.PostAsync(Dictionary`2 EndPoint, Byte[] requestContent)
   at AdysTech.InfluxDB.Client.Net.InfluxDBClient.PostPointAsync(String dbName, IInfluxDatapoint point)

**Comment by DanielPeinhopf** [comment]
Ok, i solved it by myself. It was a problem with the wrong RID.
I did use linux-arm instead of linux-arm64.
